---
- name: Add repo
  become: yes
  shell: add-apt-repository ppa:ondrej/php

- name: Install PHP and PHP packages
  become: yes
  apt:
    update_cache: yes
    pkg:
    - software-properties-common
    - php7.4
    - php7.4-cli
    - php7.4-bcmath
    - php7.4-ctype
    - php7.4-curl
    - php7.4-dom
    - php7.4-gd
    # - php7.4-hash
    - php7.4-iconv
    - php7.4-intl
    - php7.4-mbstring
    # - php7.4-openssl
    # - php7.4-pdo_mysql
    - php7.4-simplexml
    - php7.4-soap
    - php7.4-xsl
    - php7.4-zip
    - php7.4-sockets
